# Generated by Django 6.1.1 on 2026-10-05 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuTable',
            new_name='MenuList',
        ),
    ]
